apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-umami
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 3000
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-f1-micro
        databases:
          - name: reopsumami
  liveness:
    path: /isalive
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 3000
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 32Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  ingresses:
    - "https://umami.ansatt.nav.no"