name: Build, push, and deploy

on:
  push:

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs: 
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:

      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: team-researchops
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # Provided as Organization Secret
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # Provided as Organization Variable

  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: prod-gcp 
        RESOURCE: nais-prod.yaml
        IMAGE: ${{ needs.build.outputs.image }}
